# Generated by Django 4.2.11 on 2024-09-12 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_one_count', models.PositiveIntegerField(default=0)),
                ('rating_two_count', models.PositiveIntegerField(default=0)),
                ('rating_three_count', models.PositiveIntegerField(default=0)),
                ('rating_four_count', models.PositiveIntegerField(default=0)),
                ('rating_five_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('movie_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('release_date', models.DateField()),
                ('box_office_collection_in_crores', models.FloatField()),
                ('cast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imdb_project.cast')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb_project.director')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imdb_project.rating')),
            ],
        ),
        migrations.CreateModel(
            name='CastDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_debut_movie', models.BooleanField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb_project.actor')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb_project.cast')),
                ('roles', models.ManyToManyField(to='imdb_project.role')),
            ],
            options={
                'unique_together': {('cast', 'actor')},
            },
        ),
        migrations.AddField(
            model_name='cast',
            name='actors',
            field=models.ManyToManyField(through='imdb_project.CastDetails', to='imdb_project.actor'),
        ),
    ]
