# Generated by Django 4.2.11 on 2024-09-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_project', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='imdb_project.cast'),
        ),
    ]
